### ISSUE TITLE
I have a trouble in  running the code

### ISSUE THREAD

**Issue by znliunwpugmail** [malllabiisc/sictf#1]
The codes are not running successfully in my computer. Please tell me the running environment of these codes(operating system version and python version).
error messages:
![ubuntu_error](https://cloud.githubusercontent.com/assets/24560910/21171637/4af65fa2-c208-11e6-8b0f-72f060e978ee.jpg)
ubuntu
 
![windows_error](https://cloud.githubusercontent.com/assets/24560910/21171638/4b53b152-c208-11e6-8f6d-0c67ab1d44b3.png)
windows

**Comment by madhavcsa** [comment]
Please install the dependencies: numpy and scipy. The code runs with python 3.3 or above.

**Comment by znliunwpugmail** [comment]
I have already installed the dependencies: numpy,scipy,sklearn and joblib. The code ran with python3.4.3 on ubuntu16.04, and ran with python 3.4.2 on windows. But the codes didn't run succesffully.

**Comment by madhavcsa** [comment]
Please make sure that you are passing all the three files, please download data from the Data folder.

**Comment by znliunwpugmail** [comment]
![codeerror](https://cloud.githubusercontent.com/assets/24560910/21258514/4ba969ec-c3b8-11e6-800d-fdd22c1da2dd.JPG)
tensorCreatorForCNNRescalWithoutScores.py and tensorCreatorForCNNRescalWithScores.py ran succesffully, but runCRescal.py didn't run succesffully. There are error messages in the picture.

**Comment by madhavcsa** [comment]
I ran the code on my machine, I am not getting the error. I have updated the files again, just to be consistent. Could you try again with the new files and new data. I used python 3.4.2 as well.
