### ISSUE TITLE
missing file : src/filesFromData/domainNounPhrases.pkl

### ISSUE THREAD

**Issue by SeekPoint** [malllabiisc/sictf#4]
mldl@ub1604:~/ub16_prj/sictf/src$ python3 runCRescal.py . 1 10 2 100 20 15 False 0.1 0.2 0.3 0.4 0.5 
0.4
0.5
Traceback (most recent call last):
  File "runCRescal.py", line 81, in <module>
    inputHandle = open(os.path.join(os.getcwd(),fileData,'domainNounPhrases.pkl'),'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/mldl/ub16_prj/sictf/src/filesFromData/domainNounPhrases.pkl'
mldl@ub1604:~/ub16_prj/sictf/src$

**Comment by satwik77** [comment]
You must run `python3 tensorCreatorForCNNRescalWithScores.py [inputFolder] [fname] [sideInfoMatrix] [relSim]` before running `python3 runCRescal.py`. That will create `domainNounPhrases.pkl` in the required location

**Comment by SeekPoint** [comment]
mldl@ub1604:~/ub16_prj/sictf/src$ python3 tensorCreatorForCNNRescalWithScores.py ../Data/Medline Triples.txt NpSideInfo.txt RelSim.txt
Details : ['3002', '1172', '2499']
Saving files to Folder: filesFromData

Saving files to Folder: toRescal

Number of Attributes:  564
Side info matrix created

Rel Sim matrix created

Time Taken :  0.6237373710027896
mldl@ub1604:~/ub16_prj/sictf/src$


for this example， give me a workable command of 'python3 runCRescal.py ........'


thanks

**Comment by satwik77** [comment]
I updated the readme. You can directly run the commands that are mentioned the usage. To use the right parameters you can refer the paper and look where to use them in the `python3 runCRescal.py ...` based on the positional arguments mentioned in the help section.

**Comment by SeekPoint** [comment]
it works
